# Bring in data

## Bring in geometries and set CRS:

```{r, eval = FALSE}

# Brings in all MT county and census tract boundaries: 
all_counties <- counties(state = "MT")
all_tracts <- tracts(state = "MT")
# Dissolve counties for state boundary:
MT_boundary <- st_union(all_counties)

# Bring in shapefile of Tribal Nations within Montana
TribalNations <- read_sf("Shapefiles/TribalNations", "TribalNations")

# --- Transform SFs to Projected Coordinate Reference System --- #
MT_boundary <- st_transform(MT_boundary, crs = 32100)
all_tracts <- st_transform(all_tracts, crs = 32100)
all_counties <- st_transform(all_counties, crs = 32100)
TribalNations <- st_transform(TribalNations, crs = 32100)

```

## Bring in PLACES Data

```{r, eval = FALSE}

# Read in PLACES data for all available counties within Montana:
PLACES <- read.csv(file = "_tables/MT_PLACES.csv")

# decided to just keep age-adjusted prevalence values 
PLACES <- PLACES %>%
  filter(Data_Value_Type == "Age-adjusted prevalence")
  
# Calculate national median age-adjusted prevalence values for each measure
PLACES_NTL_MED <- PLACES %>%
  group_by(Measure) %>%
  summarise(national_median = median(Data_Value), 
            national_sd = sd(Data_Value), 
            Data_Value_Type = first(Data_Value_Type))

# Join national medians to original dataset 
PLACES <- PLACES %>%
  left_join(PLACES_NTL_MED)

```

## Bring in Census Data

```{r, eval = FALSE}

# Census data tables
census_data_poverty <- read_csv("_census_tables/census_data_poverty.csv")
census_data_by_FedPoverty <- read_csv("_census_tables/census_data_by_FedPoverty.csv")
census_data_veterans <- read_csv("_census_tables/census_data_Veterans.csv")
census_data_housing1 <- read_csv("_census_tables/census_data_housing1.csv")
census_data_housing2 <- read_csv("_census_tables/census_data_housing2.csv")

# County FP Codes for reference: 
COUNTYFP <- read.csv(file = "_census_tables/COUNTYFP_codes.csv")

```
